# Generated by Django 3.1.5 on 2021-01-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mouse_species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_specie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mouse_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_type', models.CharField(max_length=30)),
            ],
        ),
    ]
