# Generated by Django 3.1.5 on 2021-01-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouse_species',
            old_name='mouse_specie',
            new_name='specie_name',
        ),
        migrations.RenameField(
            model_name='mouse_type',
            old_name='mouse_type',
            new_name='type_name',
        ),
    ]
